version: "3"
services:
  autolab:
    image: linnil1/autolab
    restart: always
    environment:
      RESTFUL_HOST: tango_api
      RESTFUL_PORT: 3000
      RESTFUL_KEY: password
    # command: tail -f /dev/null
    links:
      - db
      - tango_api
    volumes:
      - ./Autolab:/app:ro
      - ./autolab/tmp:/app/tmp
      - ./autolab/log:/app/log
      - ./autolab/db:/app/db
      - ./autolab/courses:/app/courses
      - ./autolab/assessmentConfig:/app/assessmentConfig
      - ./autolab/courseConfig:/app/courseConfig
      - ./autolab/gradebooks:/app/gradebooks

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql

  web:
    image: nginx
    restart: always
    ports:
      - 13000:13000
    links:
      - autolab
    volumes:
      - ./web/autolab.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/certs/:/certs:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./autolab/web_log:/var/log/nginx/

  redis:
    image: redis
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./Tango/deployment/config/redis.conf:/etc/redis.conf

  tango_api:
    image: linnil1/tango
    restart: always
    command: python3 restful-tango/server.py
    links:
      - redis
    volumes:
    - ./Tango/:/app:ro
    - ./tango/courselabs/:/courselabs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /volume/:/volume

  tango_manager:
    image: linnil1/tango
    restart: always
    command: python3 jobManager.py
    links:
      - redis
      - web
    volumes:
    - ./Tango/:/app:ro
    - ./tango/courselabs/:/courselabs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /volume/:/volume
