version: "3"
services:
  autolab:
    image: linnil1/autolab
    build: ./build_autolab
    container_name: autolab_main
    restart: always
    environment:
      DOCKER_SSL: "false"
      # DOCKER_SSL: "true"  # set to false for no SSL (not recommended)
      HOST_PROTOCOL: http
      HOST_DOMAIN: 0.0.0.0:3000
      RESTFUL_HOST: tango_api
      RESTFUL_PORT: 3000
      RESTFUL_KEY: tango_password
      RAILS_ENV: production
      # RAILS_ENV: development
      DEVISE_SECRET_KEY: "changeThisSecret"
      SMTP_DEFAULT_FROM: admin@c4lab.tw
      SMTP_SETTINGS_ADDRESS: smtp.gmail.com
      SMTP_SETTINGS_PORT: 587
      SMTP_SETTINGS_USER_NAME: admin@c4lab.tw
      SMTP_SETTINGS_PASSWORD: email_password
      SMTP_SETTINGS_DOMAIN: c4lab.tw
    links:
      - db
      - tango_api
    ports:
      - 3000:3000
    volumes:
      - ./Autolab:/app
      - ./autolab/tmp:/app/tmp
      - ./autolab/log:/app/log
      - ./autolab/courses:/app/courses
      - ./autolab/courseConfig:/app/courseConfig
      - ./autolab/assessmentConfig:/app/assessmentConfig

  db:
    image: mysql:8.0
    restart: always
    container_name: autolab_db
    environment:
      - MYSQL_DATABASE=autolab_development
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=autolab
      - MYSQL_PASSWORD=autolab_password
    volumes:
      - ./database:/var/lib/mysql

  redis:
    image: redis
    restart: always
    container_name: autolab_redis

  tango_api:
    image: linnil1/tango
    build: ./build_tango
    container_name: autolab_tango_api
    restart: always
    command: python3 restful_tango/server.py
    links:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Tango/:/app:ro
      - ./tango/courselabs/:/courselabs
      - ./tango/volume/:/opt/TangoService/Tango/volumes
    environment:
      - DOCKER_DEPLOYMENT=prod
      - RESTFUL_KEY=tango_password
      - DOCKER_REDIS_HOSTNAME=redis
      # Path to volumes within the Tango container. Does not need to be modified.
      - DOCKER_VOLUME_PATH=/opt/TangoService/Tango/volumes
      # Modify the below to be the path to volumes on your host machine
      - DOCKER_TANGO_HOST_VOLUME_PATH=/home/linnil1/autolab/tango/volume

  tango_manager:
    image: linnil1/tango
    build: ./build_tango
    container_name: autolab_tango_main
    restart: always
    command: python3 jobManager.py
    links:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Tango/:/app:ro
      - ./tango/courselabs/:/courselabs
      - ./tango/volume/:/opt/TangoService/Tango/volumes
    environment:
      - DOCKER_DEPLOYMENT=prod
      - RESTFUL_KEY=tango_password
      - DOCKER_REDIS_HOSTNAME=redis
      # Path to volumes within the Tango container. Does not need to be modified.
      - DOCKER_VOLUME_PATH=/opt/TangoService/Tango/volumes
      # Modify the below to be the path to volumes on your host machine
      - DOCKER_TANGO_HOST_VOLUME_PATH=/home/linnil1/autolab/tango/volume
