# MySQL Configuration used for Autolab Docker Deployments
production:
  adapter: mysql2
  database: autolab_development
  pool: 5
  username: autolab
  password: autolab_password
  socket: /var/run/mysqld/mysqld.sock
  host: db
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
